@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjlhNzUxMGZhYTZlOWIxNGRmY2Q5MWFjIiwiaWF0IjoxNzcyNzk5MzU5LCJleHAiOjE3NzM0MDQxNTl9.FpZ1nf2vZRi4UC5Mi19qS0fzFgYSmgiPr8oksO9sDAs

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "user1",
  "email": "user1@mail.com",
  "password": "1234"
}

###
 
 POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "user1@mail.com",
  "password": "1234"
}

###

GET http://localhost:3000/api/characters/
Authorization: Bearer {{token}}

###

GET http://localhost:3000/api/characters?page=3&limit=4
Authorization: Bearer {{token}}

###

GET http://localhost:3000/api/characters/69a753be24df829b4e63cceb
Authorization: Bearer {{token}}

###

POST http://localhost:3000/api/characters/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": 12,
    "img": "hola.png",
    "species": "demonio",
    "age": 999999,
    "specialTraits": [],
    "role" : "Desconocido",
    "firstAppearance": "S99E99"
}

###

PUT http://localhost:3000/api/characters/69a753be24df829b4e63cceb
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Unknown",
    "species": "demonio",
    "age": 9999
}

###

DELETE http://localhost:3000/api/characters/69a753be24df829b4e63cceb
Authorization: Bearer {{token}}

###
###
###
###
###
###

GET http://localhost:3000/api/episodes
Authorization: Bearer {{token}}

###

GET http://localhost:3000/api/episodes
Authorization: Bearer {{token}}

###

GET http://localhost:3000/api/episodes?season=3
Authorization: Bearer {{token}}

###

GET http://localhost:3000/api/episodes/69a757df3e79e55ee28938f1
Authorization: Bearer {{token}}

###

POST http://localhost:3000/api/episodes/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "code": "S99E96",
    "title": "La aparicion del desconocido",
    "summary": "Lorem impum.........",
    "year": 9999,
    "characters":[
        "69a02f79b780a89df6a2eafb",
        "69a02f79b780a89df6a2eafe"
    ]
}

###

PUT http://localhost:3000/api/episodes/69a757df3e79e55ee28938f1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "year": 3333,
    "characters":[
        "69a02ccb7b15ab8294547c30",
        "69a757df3e79e55ee28938f1"
    ]
}

###

DELETE http://localhost:3000/api/episodes/69a48595e41c70f541bd1023
Authorization: Bearer {{token}}
